name: Build ESP32 Bin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Arduino Setup
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install Libs
        run: |
          arduino-cli lib install "ESP Async WebServer"
          arduino-cli lib install "AsyncTCP"
          arduino-cli lib install "Adafruit SSD1306"
          arduino-cli lib install "Adafruit GFX Library"

      - name: Compile
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir ./output sketch.ino

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: esp32-binary
          path: ./output/*.bin
